name: docker_build

on: [push]
        
env:
  GITLAB_CONTAINER_REGISTRY: gitlab-registry.cern.ch/atlas-flavor-tagging-tools/training-images/puma-images

# TODO: change all "jobirk-docker-buid" -> "main" before merging
if: github.ref == 'refs/heads/jobirk-docker-build' || startsWith(github.event.ref, 'refs/tags')

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitLab container registry
        run: docker login gitlab-registry.cern.ch -u ${{ secrets.GITLAB_USERNAME }} -p ${{ secrets.GITLAB_TOKEN }}

      - name: Build and push slim image
        if: github.ref == 'refs/heads/jobirk-docker-build'
        run: |
          docker build -f docker/Dockerfile --tag ${GITLAB_CONTAINER_REGISTRY}/puma:test .
          docker push ${GITLAB_CONTAINER_REGISTRY}/puma:test

      - name: Build and push dev image
        if: github.ref == 'refs/heads/jobirk-docker-build'
        run: |
          docker build -f docker/Dockerfile_dev --tag ${GITLAB_CONTAINER_REGISTRY}/puma:test-dev .
          docker push ${GITLAB_CONTAINER_REGISTRY}/puma:test-dev
  
      - name: Build and push release image
        # Build an extra image for tagged commits
        if: startsWith(github.event.ref, 'refs/tags')
        run: |
          docker build -f docker/Dockerfile --tag ${GITLAB_CONTAINER_REGISTRY}/puma:${{  github.ref_name  }} .
          docker push ${GITLAB_CONTAINER_REGISTRY}/puma:${{  github.ref_name  }}