name: docker_build

on:
  push:
    branches:
      - 'jobirk-docker-build'
        
env:
  GITLAB_CONTAINER_REGISTRY: gitlab-registry.cern.ch/atlas-flavor-tagging-tools/training-images/puma-images

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master
          
      - run: echo ${{  github.ref_name  }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitLab container registry
        run: docker login gitlab-registry.cern.ch -u ${{ secrets.GITLAB_USERNAME }} -p ${{ secrets.GITLAB_TOKEN }}

      - name: Build and push slim image
        run: |
          docker build -f docker/Dockerfile --tag ${GITLAB_CONTAINER_REGISTRY}/puma:test .
          docker push ${GITLAB_CONTAINER_REGISTRY}/puma:test

      - name: Build and push dev image
        run: |
          docker build -f docker/Dockerfile_dev --tag ${GITLAB_CONTAINER_REGISTRY}/puma:test-dev .
          docker push ${GITLAB_CONTAINER_REGISTRY}/puma:test-dev
  
      # - name: Build and push release image
        # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        # run: |
        #   docker build -f docker/Dockerfile_dev --tag ${GITLAB_CONTAINER_REGISTRY}/puma:test-dev .
        #   docker push ${GITLAB_CONTAINER_REGISTRY}/puma:test-dev