name: docker_build

on:
  push:
    branches:
      - 'jobirk-docker-build'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitLab container registry
        run: docker login gitlab-registry.cern.ch -u ${{ secrets.GITLAB_USERNAME }} -p ${{ secrets.GITLAB_TOKEN }}

      - name: Build slim image
        run: docker build -f docker/Dockerfile -t gitlab-registry.cern.ch/atlas-flavor-tagging-tools/training-images/puma-images/puma:test .
          
      - name: Push image to GitLab
        run: docker push gitlab-registry.cern.ch/atlas-flavor-tagging-tools/training-images/puma-images/puma:test